from stack import StringStack
from string import StringType, StringFactory
from string_manager import StringManager

if __name__ == '__main__':
    res_string = StringFactory.create(StringType.string, '123')
    hash_string = StringFactory.create(StringType.hash_string, '123456')
    string_manager = StringManager(res_string)
    hash_string_manager = StringManager(hash_string)
    stack = StringStack(res_string)
    print('StringManager ' + '-' * 100)
    print('String - ' + string_manager.string)
    print(f'Array - {string_manager.array}')
    string_manager.append('S')
    print('Append(S) - ' + string_manager.string)
    print('Get item by index - ' + string_manager[0])
    print('Get slice - ' + string_manager[2:4])
    print('HashStringManager ' + '-' * 100)
    print('String - ' + hash_string_manager.string)
    print(f'Array - {hash_string_manager.array}')
    hash_string_manager.append('S')
    print('Append(S) - ' + hash_string_manager.string)
    print('Get item by index - ' + hash_string_manager[0])
    print('Get slice - ' + hash_string_manager[2:4])
    print('Stack ' + '-' * 100)
    print(f'Initial stack - {stack.show()}')
    stack.append(string_manager)
    print(f'Append(StringManager) - {stack.show()}')
    print(f'Top element - {stack.top_element}')
    print(f'Empty - {stack.empty}')
    stack.delete()
    print(f'Delete - {stack.show()}')
